name: Notify Telegram on PR

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send notification to Telegram
        run: |
          curl -X POST "https://api.telegram.org/bot7520531803:AAGAqfxf81l_jZhxd3T0MxmNLy5KR9f-2k4/sendMessage" \
            -d chat_id=-1002266598166 \
            -d text="New PR created in the repository: ${{ github.event.pull_request.title }}. Check it out: ${{ github.event.pull_request.html_url }}"
